package com.contribute.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>address</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2018-07-16
 */
public class Address implements Serializable {
    /**
     * <pre>
     * 自增id
     * This field corresponds to the database column <tt>address.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 地址内容
     * This field corresponds to the database column <tt>address.address_content<tt>
     * </pre>
     */
    private String addressContent;

    /**
     * <pre>
     * 从属谁,商家和用户的名称
     * This field corresponds to the database column <tt>address.from_name<tt>
     * </pre>
     */
    private String fromName;

    /**
     * <pre>
     * 创建时间
     * This field corresponds to the database column <tt>address.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * 最后一次修改时间
     * This field corresponds to the database column <tt>address.gmt_update<tt>
     * </pre>
     */
    private Date gmtUpdate;

    /**
     * <pre>
     * 逻辑删除,0-未删除,1-删除,默认为0
     * This field corresponds to the database column <tt>address.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.id<tt>
     * </pre>
     *
     * @return 自增id
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.id<tt>
     * </pre>
     *
     * @param id 自增id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.address_content<tt>
     * </pre>
     *
     * @return 地址内容
     */
    public String getAddressContent() {
        return addressContent;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.address_content<tt>
     * </pre>
     *
     * @param addressContent 地址内容
     */
    public void setAddressContent(String addressContent) {
        this.addressContent = addressContent == null ? null : addressContent.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.from_name<tt>
     * </pre>
     *
     * @return 从属谁,商家和用户的名称
     */
    public String getFromName() {
        return fromName;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.from_name<tt>
     * </pre>
     *
     * @param fromName 从属谁,商家和用户的名称
     */
    public void setFromName(String fromName) {
        this.fromName = fromName == null ? null : fromName.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.gmt_create<tt>
     * </pre>
     *
     * @return 创建时间
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate 创建时间
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.gmt_update<tt>
     * </pre>
     *
     * @return 最后一次修改时间
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.gmt_update<tt>
     * </pre>
     *
     * @param gmtUpdate 最后一次修改时间
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.is_delete<tt>
     * </pre>
     *
     * @return 逻辑删除,0-未删除,1-删除,默认为0
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>address.is_delete<tt>
     * </pre>
     *
     * @param isDelete 逻辑删除,0-未删除,1-删除,默认为0
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", addressContent=").append(addressContent);
        sb.append(", fromName=").append(fromName);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Address other = (Address) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAddressContent() == null ? other.getAddressContent() == null : this.getAddressContent().equals(other.getAddressContent()))
            && (this.getFromName() == null ? other.getFromName() == null : this.getFromName().equals(other.getFromName()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtUpdate() == null ? other.getGmtUpdate() == null : this.getGmtUpdate().equals(other.getGmtUpdate()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAddressContent() == null) ? 0 : getAddressContent().hashCode());
        result = prime * result + ((getFromName() == null) ? 0 : getFromName().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtUpdate() == null) ? 0 : getGmtUpdate().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}