package com.contribute.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>content</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2018-07-16
 */
public class Content implements Serializable {
    /**
     * <pre>
     * 自增di
     * This field corresponds to the database column <tt>content.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 用户id
     * This field corresponds to the database column <tt>content.user_id<tt>
     * </pre>
     */
    private Long userId;

    /**
     * <pre>
     * 商家id
     * This field corresponds to the database column <tt>content.shop_id<tt>
     * </pre>
     */
    private Long shopId;

    /**
     * <pre>
     * 商品id
     * This field corresponds to the database column <tt>content.merchandise_id<tt>
     * </pre>
     */
    private Long merchandiseId;

    /**
     * <pre>
     * 评论内容
     * This field corresponds to the database column <tt>content.content_text<tt>
     * </pre>
     */
    private String contentText;

    /**
     * <pre>
     * 是否匿名,0-不匿名,1-匿名,默认为0
     * This field corresponds to the database column <tt>content.is_anonymous<tt>
     * </pre>
     */
    private Integer isAnonymous;

    /**
     * <pre>
     * 评论时间
     * This field corresponds to the database column <tt>content.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * 修改时间
     * This field corresponds to the database column <tt>content.gmt_update<tt>
     * </pre>
     */
    private Date gmtUpdate;

    /**
     * <pre>
     * 逻辑删除,0-未删除,1-删除,默认为0
     * This field corresponds to the database column <tt>content.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.id<tt>
     * </pre>
     *
     * @return 自增di
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.id<tt>
     * </pre>
     *
     * @param id 自增di
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.user_id<tt>
     * </pre>
     *
     * @return 用户id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.user_id<tt>
     * </pre>
     *
     * @param userId 用户id
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.shop_id<tt>
     * </pre>
     *
     * @return 商家id
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.shop_id<tt>
     * </pre>
     *
     * @param shopId 商家id
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.merchandise_id<tt>
     * </pre>
     *
     * @return 商品id
     */
    public Long getMerchandiseId() {
        return merchandiseId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.merchandise_id<tt>
     * </pre>
     *
     * @param merchandiseId 商品id
     */
    public void setMerchandiseId(Long merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.content_text<tt>
     * </pre>
     *
     * @return 评论内容
     */
    public String getContentText() {
        return contentText;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.content_text<tt>
     * </pre>
     *
     * @param contentText 评论内容
     */
    public void setContentText(String contentText) {
        this.contentText = contentText == null ? null : contentText.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.is_anonymous<tt>
     * </pre>
     *
     * @return 是否匿名,0-不匿名,1-匿名,默认为0
     */
    public Integer getIsAnonymous() {
        return isAnonymous;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.is_anonymous<tt>
     * </pre>
     *
     * @param isAnonymous 是否匿名,0-不匿名,1-匿名,默认为0
     */
    public void setIsAnonymous(Integer isAnonymous) {
        this.isAnonymous = isAnonymous;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.gmt_create<tt>
     * </pre>
     *
     * @return 评论时间
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate 评论时间
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.gmt_update<tt>
     * </pre>
     *
     * @return 修改时间
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.gmt_update<tt>
     * </pre>
     *
     * @param gmtUpdate 修改时间
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.is_delete<tt>
     * </pre>
     *
     * @return 逻辑删除,0-未删除,1-删除,默认为0
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>content.is_delete<tt>
     * </pre>
     *
     * @param isDelete 逻辑删除,0-未删除,1-删除,默认为0
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", shopId=").append(shopId);
        sb.append(", merchandiseId=").append(merchandiseId);
        sb.append(", contentText=").append(contentText);
        sb.append(", isAnonymous=").append(isAnonymous);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Content other = (Content) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getShopId() == null ? other.getShopId() == null : this.getShopId().equals(other.getShopId()))
            && (this.getMerchandiseId() == null ? other.getMerchandiseId() == null : this.getMerchandiseId().equals(other.getMerchandiseId()))
            && (this.getContentText() == null ? other.getContentText() == null : this.getContentText().equals(other.getContentText()))
            && (this.getIsAnonymous() == null ? other.getIsAnonymous() == null : this.getIsAnonymous().equals(other.getIsAnonymous()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtUpdate() == null ? other.getGmtUpdate() == null : this.getGmtUpdate().equals(other.getGmtUpdate()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getShopId() == null) ? 0 : getShopId().hashCode());
        result = prime * result + ((getMerchandiseId() == null) ? 0 : getMerchandiseId().hashCode());
        result = prime * result + ((getContentText() == null) ? 0 : getContentText().hashCode());
        result = prime * result + ((getIsAnonymous() == null) ? 0 : getIsAnonymous().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtUpdate() == null) ? 0 : getGmtUpdate().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}