package com.contribute.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>user</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2018-07-16
 */
public class User implements Serializable {
    /**
     * <pre>
     * 自增id
     * This field corresponds to the database column <tt>user.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 用户名
     * This field corresponds to the database column <tt>user.user_name<tt>
     * </pre>
     */
    private String userName;

    /**
     * <pre>
     * 用户邮箱
     * This field corresponds to the database column <tt>user.user_email<tt>
     * </pre>
     */
    private String userEmail;

    /**
     * <pre>
     * 用户密码
     * This field corresponds to the database column <tt>user.user_password<tt>
     * </pre>
     */
    private String userPassword;

    /**
     * <pre>
     * 加密盐
     * This field corresponds to the database column <tt>user.user_salt<tt>
     * </pre>
     */
    private String userSalt;

    /**
     * <pre>
     * 用户电话号码
     * This field corresponds to the database column <tt>user.user_number<tt>
     * </pre>
     */
    private String userNumber;

    /**
     * <pre>
     * 创建时间
     * This field corresponds to the database column <tt>user.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * 更改时间
     * This field corresponds to the database column <tt>user.gmt_update<tt>
     * </pre>
     */
    private Date gmtUpdate;

    /**
     * <pre>
     * 逻辑删除,0-未删除，1-删除
     * This field corresponds to the database column <tt>user.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.id<tt>
     * </pre>
     *
     * @return 自增id
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.id<tt>
     * </pre>
     *
     * @param id 自增id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_name<tt>
     * </pre>
     *
     * @return 用户名
     */
    public String getUserName() {
        return userName;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_name<tt>
     * </pre>
     *
     * @param userName 用户名
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_email<tt>
     * </pre>
     *
     * @return 用户邮箱
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_email<tt>
     * </pre>
     *
     * @param userEmail 用户邮箱
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_password<tt>
     * </pre>
     *
     * @return 用户密码
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_password<tt>
     * </pre>
     *
     * @param userPassword 用户密码
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_salt<tt>
     * </pre>
     *
     * @return 加密盐
     */
    public String getUserSalt() {
        return userSalt;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_salt<tt>
     * </pre>
     *
     * @param userSalt 加密盐
     */
    public void setUserSalt(String userSalt) {
        this.userSalt = userSalt == null ? null : userSalt.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_number<tt>
     * </pre>
     *
     * @return 用户电话号码
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.user_number<tt>
     * </pre>
     *
     * @param userNumber 用户电话号码
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.gmt_create<tt>
     * </pre>
     *
     * @return 创建时间
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate 创建时间
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.gmt_update<tt>
     * </pre>
     *
     * @return 更改时间
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.gmt_update<tt>
     * </pre>
     *
     * @param gmtUpdate 更改时间
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.is_delete<tt>
     * </pre>
     *
     * @return 逻辑删除,0-未删除，1-删除
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>user.is_delete<tt>
     * </pre>
     *
     * @param isDelete 逻辑删除,0-未删除，1-删除
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userPassword=").append(userPassword);
        sb.append(", userSalt=").append(userSalt);
        sb.append(", userNumber=").append(userNumber);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserEmail() == null ? other.getUserEmail() == null : this.getUserEmail().equals(other.getUserEmail()))
            && (this.getUserPassword() == null ? other.getUserPassword() == null : this.getUserPassword().equals(other.getUserPassword()))
            && (this.getUserSalt() == null ? other.getUserSalt() == null : this.getUserSalt().equals(other.getUserSalt()))
            && (this.getUserNumber() == null ? other.getUserNumber() == null : this.getUserNumber().equals(other.getUserNumber()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtUpdate() == null ? other.getGmtUpdate() == null : this.getGmtUpdate().equals(other.getGmtUpdate()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserEmail() == null) ? 0 : getUserEmail().hashCode());
        result = prime * result + ((getUserPassword() == null) ? 0 : getUserPassword().hashCode());
        result = prime * result + ((getUserSalt() == null) ? 0 : getUserSalt().hashCode());
        result = prime * result + ((getUserNumber() == null) ? 0 : getUserNumber().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtUpdate() == null) ? 0 : getGmtUpdate().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}