package entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>merchandise</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2018-06-21
 */
public class Merchandise implements Serializable {
    /**
     * <pre>
     * 自增id
     * This field corresponds to the database column <tt>merchandise.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 商品编号
     * This field corresponds to the database column <tt>merchandise.merchandise_code<tt>
     * </pre>
     */
    private String merchandiseCode;

    /**
     * <pre>
     * 商品名称
     * This field corresponds to the database column <tt>merchandise.merchandise_name<tt>
     * </pre>
     */
    private String merchandiseName;

    /**
     * <pre>
     * 商品描述
     * This field corresponds to the database column <tt>merchandise.merchandise_content<tt>
     * </pre>
     */
    private String merchandiseContent;

    /**
     * <pre>
     * 商品价格
     * This field corresponds to the database column <tt>merchandise.merchandise_price<tt>
     * </pre>
     */
    private Double merchandisePrice;

    /**
     * <pre>
     * 商品数量
     * This field corresponds to the database column <tt>merchandise.merchandise_number<tt>
     * </pre>
     */
    private Integer merchandiseNumber;

    /**
     * <pre>
     * 商品厂家
     * This field corresponds to the database column <tt>merchandise.merchandise_factory<tt>
     * </pre>
     */
    private String merchandiseFactory;

    /**
     * <pre>
     * 出厂日期
     * This field corresponds to the database column <tt>merchandise.merchandise_birthday<tt>
     * </pre>
     */
    private Date merchandiseBirthday;

    /**
     * <pre>
     * 商品种类id
     * This field corresponds to the database column <tt>merchandise.merchandise_category_id<tt>
     * </pre>
     */
    private Integer merchandiseCategoryId;

    /**
     * <pre>
     * 商品从属的店家id
     * This field corresponds to the database column <tt>merchandise.merchandise_shop_id<tt>
     * </pre>
     */
    private Long merchandiseShopId;

    /**
     * <pre>
     * 
     * This field corresponds to the database column <tt>merchandise.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * 最后一次更改时间
     * This field corresponds to the database column <tt>merchandise.gmt_update<tt>
     * </pre>
     */
    private Date gmtUpdate;

    /**
     * <pre>
     * 逻辑删除,0-未删除,1-删除,默认为0
     * This field corresponds to the database column <tt>merchandise.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.id<tt>
     * </pre>
     *
     * @return 自增id
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.id<tt>
     * </pre>
     *
     * @param id 自增id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_code<tt>
     * </pre>
     *
     * @return 商品编号
     */
    public String getMerchandiseCode() {
        return merchandiseCode;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_code<tt>
     * </pre>
     *
     * @param merchandiseCode 商品编号
     */
    public void setMerchandiseCode(String merchandiseCode) {
        this.merchandiseCode = merchandiseCode == null ? null : merchandiseCode.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_name<tt>
     * </pre>
     *
     * @return 商品名称
     */
    public String getMerchandiseName() {
        return merchandiseName;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_name<tt>
     * </pre>
     *
     * @param merchandiseName 商品名称
     */
    public void setMerchandiseName(String merchandiseName) {
        this.merchandiseName = merchandiseName == null ? null : merchandiseName.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_content<tt>
     * </pre>
     *
     * @return 商品描述
     */
    public String getMerchandiseContent() {
        return merchandiseContent;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_content<tt>
     * </pre>
     *
     * @param merchandiseContent 商品描述
     */
    public void setMerchandiseContent(String merchandiseContent) {
        this.merchandiseContent = merchandiseContent == null ? null : merchandiseContent.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_price<tt>
     * </pre>
     *
     * @return 商品价格
     */
    public Double getMerchandisePrice() {
        return merchandisePrice;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_price<tt>
     * </pre>
     *
     * @param merchandisePrice 商品价格
     */
    public void setMerchandisePrice(Double merchandisePrice) {
        this.merchandisePrice = merchandisePrice;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_number<tt>
     * </pre>
     *
     * @return 商品数量
     */
    public Integer getMerchandiseNumber() {
        return merchandiseNumber;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_number<tt>
     * </pre>
     *
     * @param merchandiseNumber 商品数量
     */
    public void setMerchandiseNumber(Integer merchandiseNumber) {
        this.merchandiseNumber = merchandiseNumber;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_factory<tt>
     * </pre>
     *
     * @return 商品厂家
     */
    public String getMerchandiseFactory() {
        return merchandiseFactory;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_factory<tt>
     * </pre>
     *
     * @param merchandiseFactory 商品厂家
     */
    public void setMerchandiseFactory(String merchandiseFactory) {
        this.merchandiseFactory = merchandiseFactory == null ? null : merchandiseFactory.trim();
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_birthday<tt>
     * </pre>
     *
     * @return 出厂日期
     */
    public Date getMerchandiseBirthday() {
        return merchandiseBirthday;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_birthday<tt>
     * </pre>
     *
     * @param merchandiseBirthday 出厂日期
     */
    public void setMerchandiseBirthday(Date merchandiseBirthday) {
        this.merchandiseBirthday = merchandiseBirthday;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_category_id<tt>
     * </pre>
     *
     * @return 商品种类id
     */
    public Integer getMerchandiseCategoryId() {
        return merchandiseCategoryId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_category_id<tt>
     * </pre>
     *
     * @param merchandiseCategoryId 商品种类id
     */
    public void setMerchandiseCategoryId(Integer merchandiseCategoryId) {
        this.merchandiseCategoryId = merchandiseCategoryId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_shop_id<tt>
     * </pre>
     *
     * @return 商品从属的店家id
     */
    public Long getMerchandiseShopId() {
        return merchandiseShopId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.merchandise_shop_id<tt>
     * </pre>
     *
     * @param merchandiseShopId 商品从属的店家id
     */
    public void setMerchandiseShopId(Long merchandiseShopId) {
        this.merchandiseShopId = merchandiseShopId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.gmt_create<tt>
     * </pre>
     *
     * @return 
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate 
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.gmt_update<tt>
     * </pre>
     *
     * @return 最后一次更改时间
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.gmt_update<tt>
     * </pre>
     *
     * @param gmtUpdate 最后一次更改时间
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.is_delete<tt>
     * </pre>
     *
     * @return 逻辑删除,0-未删除,1-删除,默认为0
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>merchandise.is_delete<tt>
     * </pre>
     *
     * @param isDelete 逻辑删除,0-未删除,1-删除,默认为0
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", merchandiseCode=").append(merchandiseCode);
        sb.append(", merchandiseName=").append(merchandiseName);
        sb.append(", merchandiseContent=").append(merchandiseContent);
        sb.append(", merchandisePrice=").append(merchandisePrice);
        sb.append(", merchandiseNumber=").append(merchandiseNumber);
        sb.append(", merchandiseFactory=").append(merchandiseFactory);
        sb.append(", merchandiseBirthday=").append(merchandiseBirthday);
        sb.append(", merchandiseCategoryId=").append(merchandiseCategoryId);
        sb.append(", merchandiseShopId=").append(merchandiseShopId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Merchandise other = (Merchandise) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMerchandiseCode() == null ? other.getMerchandiseCode() == null : this.getMerchandiseCode().equals(other.getMerchandiseCode()))
            && (this.getMerchandiseName() == null ? other.getMerchandiseName() == null : this.getMerchandiseName().equals(other.getMerchandiseName()))
            && (this.getMerchandiseContent() == null ? other.getMerchandiseContent() == null : this.getMerchandiseContent().equals(other.getMerchandiseContent()))
            && (this.getMerchandisePrice() == null ? other.getMerchandisePrice() == null : this.getMerchandisePrice().equals(other.getMerchandisePrice()))
            && (this.getMerchandiseNumber() == null ? other.getMerchandiseNumber() == null : this.getMerchandiseNumber().equals(other.getMerchandiseNumber()))
            && (this.getMerchandiseFactory() == null ? other.getMerchandiseFactory() == null : this.getMerchandiseFactory().equals(other.getMerchandiseFactory()))
            && (this.getMerchandiseBirthday() == null ? other.getMerchandiseBirthday() == null : this.getMerchandiseBirthday().equals(other.getMerchandiseBirthday()))
            && (this.getMerchandiseCategoryId() == null ? other.getMerchandiseCategoryId() == null : this.getMerchandiseCategoryId().equals(other.getMerchandiseCategoryId()))
            && (this.getMerchandiseShopId() == null ? other.getMerchandiseShopId() == null : this.getMerchandiseShopId().equals(other.getMerchandiseShopId()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtUpdate() == null ? other.getGmtUpdate() == null : this.getGmtUpdate().equals(other.getGmtUpdate()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMerchandiseCode() == null) ? 0 : getMerchandiseCode().hashCode());
        result = prime * result + ((getMerchandiseName() == null) ? 0 : getMerchandiseName().hashCode());
        result = prime * result + ((getMerchandiseContent() == null) ? 0 : getMerchandiseContent().hashCode());
        result = prime * result + ((getMerchandisePrice() == null) ? 0 : getMerchandisePrice().hashCode());
        result = prime * result + ((getMerchandiseNumber() == null) ? 0 : getMerchandiseNumber().hashCode());
        result = prime * result + ((getMerchandiseFactory() == null) ? 0 : getMerchandiseFactory().hashCode());
        result = prime * result + ((getMerchandiseBirthday() == null) ? 0 : getMerchandiseBirthday().hashCode());
        result = prime * result + ((getMerchandiseCategoryId() == null) ? 0 : getMerchandiseCategoryId().hashCode());
        result = prime * result + ((getMerchandiseShopId() == null) ? 0 : getMerchandiseShopId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtUpdate() == null) ? 0 : getGmtUpdate().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}