package entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class corresponds to the database table <tt>shopping_cart_merchandise</tt>
 * 
 * This file is generated by <tt>dwframe<tt>
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to find the file
 * <tt>{project-home}/dalgen/mybatis_generator.xml<tt>. Modify the configuration file
 * according to your needs, then run <tt>ant</tt> to generate this file in {project-home}/dalgen.
 * 
 * @author dwframe
 * @since 2018-06-21
 */
public class ShoppingCartMerchandise implements Serializable {
    /**
     * <pre>
     * 自增id
     * This field corresponds to the database column <tt>shopping_cart_merchandise.id<tt>
     * </pre>
     */
    private Long id;

    /**
     * <pre>
     * 购物车id
     * This field corresponds to the database column <tt>shopping_cart_merchandise.shopping_cart_id<tt>
     * </pre>
     */
    private Long shoppingCartId;

    /**
     * <pre>
     * 商品id
     * This field corresponds to the database column <tt>shopping_cart_merchandise.merchandise_id<tt>
     * </pre>
     */
    private Long merchandiseId;

    /**
     * <pre>
     * 商品数量
     * This field corresponds to the database column <tt>shopping_cart_merchandise.merchandise_number<tt>
     * </pre>
     */
    private Integer merchandiseNumber;

    /**
     * <pre>
     * 创建时间
     * This field corresponds to the database column <tt>shopping_cart_merchandise.gmt_create<tt>
     * </pre>
     */
    private Date gmtCreate;

    /**
     * <pre>
     * 修改时间
     * This field corresponds to the database column <tt>shopping_cart_merchandise.gmt_update<tt>
     * </pre>
     */
    private Date gmtUpdate;

    /**
     * <pre>
     * 逻辑删除,0-未删除,1-删除,默认为0
     * This field corresponds to the database column <tt>shopping_cart_merchandise.is_delete<tt>
     * </pre>
     */
    private Integer isDelete;

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.id<tt>
     * </pre>
     *
     * @return 自增id
     */
    public Long getId() {
        return id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.id<tt>
     * </pre>
     *
     * @param id 自增id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.shopping_cart_id<tt>
     * </pre>
     *
     * @return 购物车id
     */
    public Long getShoppingCartId() {
        return shoppingCartId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.shopping_cart_id<tt>
     * </pre>
     *
     * @param shoppingCartId 购物车id
     */
    public void setShoppingCartId(Long shoppingCartId) {
        this.shoppingCartId = shoppingCartId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.merchandise_id<tt>
     * </pre>
     *
     * @return 商品id
     */
    public Long getMerchandiseId() {
        return merchandiseId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.merchandise_id<tt>
     * </pre>
     *
     * @param merchandiseId 商品id
     */
    public void setMerchandiseId(Long merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.merchandise_number<tt>
     * </pre>
     *
     * @return 商品数量
     */
    public Integer getMerchandiseNumber() {
        return merchandiseNumber;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.merchandise_number<tt>
     * </pre>
     *
     * @param merchandiseNumber 商品数量
     */
    public void setMerchandiseNumber(Integer merchandiseNumber) {
        this.merchandiseNumber = merchandiseNumber;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.gmt_create<tt>
     * </pre>
     *
     * @return 创建时间
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.gmt_create<tt>
     * </pre>
     *
     * @param gmtCreate 创建时间
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.gmt_update<tt>
     * </pre>
     *
     * @return 修改时间
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.gmt_update<tt>
     * </pre>
     *
     * @param gmtUpdate 修改时间
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.is_delete<tt>
     * </pre>
     *
     * @return 逻辑删除,0-未删除,1-删除,默认为0
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * <pre>
     * This field corresponds to the database column <tt>shopping_cart_merchandise.is_delete<tt>
     * </pre>
     *
     * @param isDelete 逻辑删除,0-未删除,1-删除,默认为0
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shoppingCartId=").append(shoppingCartId);
        sb.append(", merchandiseId=").append(merchandiseId);
        sb.append(", merchandiseNumber=").append(merchandiseNumber);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", isDelete=").append(isDelete);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShoppingCartMerchandise other = (ShoppingCartMerchandise) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getShoppingCartId() == null ? other.getShoppingCartId() == null : this.getShoppingCartId().equals(other.getShoppingCartId()))
            && (this.getMerchandiseId() == null ? other.getMerchandiseId() == null : this.getMerchandiseId().equals(other.getMerchandiseId()))
            && (this.getMerchandiseNumber() == null ? other.getMerchandiseNumber() == null : this.getMerchandiseNumber().equals(other.getMerchandiseNumber()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtUpdate() == null ? other.getGmtUpdate() == null : this.getGmtUpdate().equals(other.getGmtUpdate()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getShoppingCartId() == null) ? 0 : getShoppingCartId().hashCode());
        result = prime * result + ((getMerchandiseId() == null) ? 0 : getMerchandiseId().hashCode());
        result = prime * result + ((getMerchandiseNumber() == null) ? 0 : getMerchandiseNumber().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtUpdate() == null) ? 0 : getGmtUpdate().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}